name: Deploy to Render via Terraform

on:
    push:
        branches:
            - main

permissions: 
    contents: read
    pull-requests: write

jobs:
  terraform:
    name: Terraform Deploy
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./iac 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -no-color -input=false
        env:
          TF_VAR_RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          TF_VAR_RENDER_OWNER_ID: ${{ secrets.RENDER_OWNER_ID }}
          TF_VAR_DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          TF_VAR_APP_ID: ${{secrets.APP_ID}}
          TF_VAR_GUILD_ID: ${{secrets.GUILD_ID}}
          TF_VAR_PUBLIC_KEY: ${{secrets.PUBLIC_KEY}}

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve -input=false
        env:
          TF_VAR_RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          TF_VAR_RENDER_OWNER_ID: ${{ secrets.RENDER_OWNER_ID }}
          TF_VAR_DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          TF_VAR_APP_ID: ${{secrets.APP_ID}}
          TF_VAR_GUILD_ID: ${{secrets.GUILD_ID}}
          TF_VAR_PUBLIC_KEY: ${{secrets.PUBLIC_KEY}}